name: Publish Python distributions to PyPI and TestPyPI

on:
    push:
    branches: [ main ]
    pull_request:
    branches: [ main ]

jobs:
    build:
      name: Build and publish Python distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Initialize Python
        uses: actions/setup-python@v1
        with:
            python-version: 3.8
        - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
        - name: Build binary wheel and a source tarball
        run: python -m build
